config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get    'sessions/new'
  get    'users/new'
  root   'dash_board#home'
  get    '/home',    to: 'dash_board#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
 # get    '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :projects 
  resources :accesses
  resources :comments
  resources :features do
    member do
      patch "document"
    end
  end
  resources :tasks do
    member do
      patch "status"
      patch "done"
      patch "user_id"
    end
  end
  get '/features', to: 'projects#show'
  get '/projects/:id/currentiteration', to:'projects#currentiteration', as: 'currentiteration_project'
  get '/projects/:id/backlog', to:'projects#backlog', as: 'backlog_project'
  get '/projects/:id/icebox', to:'projects#icebox', as: 'icebox_project'
  post '/tasks/:id/edit', to:'comments#create'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :feature
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if logged_in?
		  @tasks= Task.all
    else
      redirect_to login_path
    end
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Task created!"
      redirect_to request.referrer
    else
      render 'projects/index'
    end
  end

  def show
    @task = Task.find_by_id(params[:id])
  end
  
  def destroy
  end

  def edit
    @task = Task.find(params[:id])
    render :edit
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(params.require(:task).permit(:content, :status))
      flash[:success] = "Task item successfully updated!"
      redirect_to request.referrer
    else
      flash.now[:error] = "Task item update failed"
      render :edit
    end
  end

  def status
    @task = Task.find(params[:id])
    @task.update_attribute(:status, params[:status])
    redirect_back(fallback_location: root_path, flash: { notice: "Task status updated" })
  end

  def done
    @task = Task.find(params[:id])
    if @task.update_attribute(:done, params[:Done])
      redirect_to request.referrer
    else
      flash.now[:error] = "Done failed"
    end
  end

  def user_id
    @task = Task.find(params[:id])
    if @task.update_attribute(:user_id, params[:user_id])
      @user_r = params[:user_id]
      TaskMailer.with(user_id: @user_r, task: @task).task_assigned.deliver_now
      flash[:success] = "Member Assigned and Email sent."
      redirect_to request.referrer
    else
      flash.now[:error] = "Member Not Assigned"
    end
  end

  private

  def task_params
    params.require(:task).permit(:content, :status, :feature_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<%= form_with model: @task, url: task_path(@task), method: :patch, local: true do |f| %>
  <%= f.hidden_field :feature_id, value: @feature_id %>
  <%= render 'shared/error_messages', object: @task %>
  <div class="field", id="tasknew">
    <div class="field", id="tasknew">
      <%= f.label :content,"Task Content" %>
      <%= f.text_field :content, class: "form-control", placeholder: "Task content", required: true %>
    </div>
    <%= f.select :status,["Started","Finished","Delivered"],class:"form-control me-2" %>
    <%= f.submit "Update Task", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

<%= link_to "Back", 'javascript:history.back()', class: "btn btn-outline-secondary" %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<br>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= task.content %>
      <%= task.feature_id %>
      
    </li>
  <% end %>
</ul>

app/views/tasks/show.html.erb
<%= " This is show page" %>
<% @fea=Feature.find_by(id: @task.feature_id) %>

<br>
<table class="table table-responsive table-hover">
  <tr >
    <%= check_box_tag 'Done', true , @task.done,
          onchange: "$(this).data('params',  this.checked)",
          data: { remote: true, url: done_task_path(id: @task.id), method: :patch } %>
  </tr>
  <tr><strong><%= @task.content%></strong></tr><br>
  <tr><strong>&nbsp;<%= " Task status: " %></strong><%= @task.status %></tr><br>
  <tr><strong>&nbsp;<%= " Feature Title: " %></strong><%= @fea.Title %></tr><br>
</table>