config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get    'sessions/new'
  get    'users/new'
  root   'dash_board#home'
  get    '/home',    to: 'dash_board#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
 # get    '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :projects 
  resources :accesses
  resources :comments
  resources :features do
    member do
      patch "document"
    end
  end
  resources :tasks do
    member do
      patch "status"
      patch "done"
      patch "user_id"
    end
  end
  get '/features', to: 'projects#show'
  get '/projects/:id/currentiteration', to:'projects#currentiteration', as: 'currentiteration_project'
  get '/projects/:id/backlog', to:'projects#backlog', as: 'backlog_project'
  get '/projects/:id/icebox', to:'projects#icebox', as: 'icebox_project'
  post '/tasks/:id/edit', to:'comments#create'
end

app/models/feature.rb
class Feature < ApplicationRecord
  before_validation :set_token_id
  belongs_to :project
  has_many :tasks, dependent: :destroy
  has_many_attached :documents
  validates :project_id, presence: true
  validates :Title, presence: true, length: { maximum: 140 }
  validates :Description, presence: true
  validates :Category, presence: true
  validates :token_id, uniqueness: true
  validate :validate_document_filetypes

  def set_token_id
    self.token_id = "F"+ Random.hex(4)
  end

  def validate_document_filetypes
    return unless documents.attached?
    documents.each do |document|
      unless document.content_type.in?(%w[image/jpeg image/png application/pdf application/vnd.ms-excel application/vnd.openxmlformats-officedocument.wordprocessingml.document])
        errors.add(:documents, 'Invalid file type')
      end
    end 
  end


end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  
  def index
    if logged_in?
		  @features= Feature.all
    else
      redirect_to login_path
    end
  end

  def show
    if logged_in?
      @feature = Feature.find_by_id(params[:id])
      @tasks = Task.all
    else
      redirect_to login_path
    end
	end


  def create
    @feature = Feature.new(feature_params)
    if @feature.save
      flash[:success] = "Feature created!"
      redirect_to request.referrer
    else
      render 'projects/index'
    end
  end

  def destroy
    @fea = Feature.find_by_id(params[:id])
    @t_d = Task.where(:feature_id => @fea.id)
    @t_d.each do |i|
      i.destroy  
    end
    @fea.destroy
    flash[:success] = "Feature deleted"
    redirect_to projects_path, :notice => "feature deleted"
  end

  def document
    @feature = Feature.find_by_id(params[:id])
    if @feature.update(document_params)
      flash[:success] = "File uploaded"
    else
      flash[:danger] = "Invalid File type (jpeg, png, pdf, doc and xls accepted)"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def feature_params
    params.require(:feature).permit(:Title, :Description, :Category, :project_id)
  end

  def document_params
    params.require(:feature).permit(documents: [])
  end

end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_feature.html.erb
<li id="feature-<%= feature.id %>">
  <span class="project"><%= link_to feature.project.name, feature.project %></span>
  <span class="title"><%= feature.title %></span>
  <span class="description"><%= feature.description %></span>
  <span class="category"><%= feature.category %></span>

</li>

app/views/features/index.html.erb
<ul>
  <% @features.each do |feature| %>
    <li>
      <%= link_to feature.Title, feature %>
    </li>
  <% end %>
</ul>

app/views/features/new.html.erb
<%= render 'shared/feature_form' %>

app/views/features/show.html.erb
<h1><%= @feature.Title %><br></h1>
<% task = Task.new %>
<% feature_task = Task.where(feature_id: @feature.id) %>
<% if feature_task.count == 0%>
  <h2> <%= "No Task Found" %> </h2> <br>
<% else %>
  <h4><%= "Tasks:" %><strong><%= feature_task.where(done: true).count() %><%= "/" %><%= feature_task.count() %></strong></h4>
  <table class="table table-responsive table-hover">
    <% @u_id = current_user.id %>
    <thead>
      <tr>
        <th> <%= "Content" %> </th>
        <th> <%= "Status" %> </th>
        <th> <%= "Member" %> </th>
      </tr>
    </thead>
    <tbody> 
      <% feature_task.each do |t| %>
        <tr>
          <th> <%= t.content %> </th>
          <th> <%= t.status %> </th>
          <th> <% c= User.where(id: t.user_id) %>
            <% if c.count() == 0 %>
              <%= "Task not Assigned" %>
            <% else %>
              <%= c[0].name %>
            <% end %>
          </th>
          <th>
            <div>
              <% @t_id = t.id %>
              <% @comment = Comment.new %>
              <%= form_with(model: @comment, local: true) do |f| %>
                <%= f.hidden_field :user_id, value: @u_id %>
                <%= f.hidden_field :task_id, value: @t_id %>
                <div class="field">
                  <%= f.text_field :body, placeholder: "New Comment:  Press Enter", class:"form-control me-2", id: "submit_on_enter" %>
                </div>      
              <% end %>
            </div>
          </th>
          <th><%= link_to "Edit",edit_task_path(id: t.id), class: "btn btn-primary", role: "button" %></th>
        </tr>
        <% @comments = Comment.where(task_id: t.id) %>
        <% @cc=0 %>
        <% @comments.each do |i| %>
          <% @cc = @cc+1 %>
          <tr>
            <% @u = i.user.name %>
            <td> <strong><%= "c-#{@cc}: "%></strong><%=  markdown(i.body) %> </td>
            <td> <%="By: "+ @u %> </td>
            <td><%= link_to 'Delete', comment_path(:id => i.id),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% if @feature.documents.attached? %>
      <div class="col-md">
        <strong><%= "Document Attached : " %></strong>
        <div class="d-flex" style="gap:25px">
          <% @feature.documents.includes([:blob]).each do |document| %>
            <div class="d-flex flex-column ", style="gap: 25px;">
              <%= link_to document.filename , rails_blob_path(document, disposition: "inline"), target: "_blank" %>
              <%= link_to "Download" , rails_blob_path(document, disposition: "attachment"),class:"btn btn-outline-secondary", target: "_blank" %>
            </div>
          <% end %>
        </div>
      </div>
  <% end %>
      <%= form_with model: @feature, url: document_feature_url(id: @feature.id) do |f|%>
        <div class="field", id="tasknew">
          <%= f.file_field :documents, multiple: true, :class => "form-control" %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
<% end %>
<%= link_to "Back", 'javascript:history.back()',class: "btn btn-primary" %>