config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get    'sessions/new'
  get    'users/new'
  root   'dash_board#home'
  get    '/home',    to: 'dash_board#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
 # get    '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :projects 
  resources :accesses
  resources :comments
  resources :features do
    member do
      patch "document"
    end
  end
  resources :tasks do
    member do
      patch "status"
      patch "done"
      patch "user_id"
    end
  end
  get '/features', to: 'projects#show'
  get '/projects/:id/currentiteration', to:'projects#currentiteration', as: 'currentiteration_project'
  get '/projects/:id/backlog', to:'projects#backlog', as: 'backlog_project'
  get '/projects/:id/icebox', to:'projects#icebox', as: 'icebox_project'
  post '/tasks/:id/edit', to:'comments#create'
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates_uniqueness_of :project_id, :scope => [:user_id], :message => "Already given"
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/feature.rb
class Feature < ApplicationRecord
  before_validation :set_token_id
  belongs_to :project
  has_many :tasks, dependent: :destroy
  has_many_attached :documents
  validates :project_id, presence: true
  validates :Title, presence: true, length: { maximum: 140 }
  validates :Description, presence: true
  validates :Category, presence: true
  validates :token_id, uniqueness: true
  validate :validate_document_filetypes

  def set_token_id
    self.token_id = "F"+ Random.hex(4)
  end

  def validate_document_filetypes
    return unless documents.attached?
    documents.each do |document|
      unless document.content_type.in?(%w[image/jpeg image/png application/pdf application/vnd.ms-excel application/vnd.openxmlformats-officedocument.wordprocessingml.document])
        errors.add(:documents, 'Invalid file type')
      end
    end 
  end


end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    has_many :features, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :feature
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format:   { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if logged_in?
      @query = Feature.ransack(params[:q])
      @features = @query.result(distinct: true)
    else
      redirect_to login_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if logged_in?
		  @tasks= Task.all
    else
      redirect_to login_path
    end
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Task created!"
      redirect_to request.referrer
    else
      render 'projects/index'
    end
  end

  def show
    @task = Task.find_by_id(params[:id])
  end
  
  def destroy
  end

  def edit
    @task = Task.find(params[:id])
    render :edit
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(params.require(:task).permit(:content, :status))
      flash[:success] = "Task item successfully updated!"
      redirect_to request.referrer
    else
      flash.now[:error] = "Task item update failed"
      render :edit
    end
  end

  def status
    @task = Task.find(params[:id])
    @task.update_attribute(:status, params[:status])
    redirect_back(fallback_location: root_path, flash: { notice: "Task status updated" })
  end

  def done
    @task = Task.find(params[:id])
    if @task.update_attribute(:done, params[:Done])
      redirect_to request.referrer
    else
      flash.now[:error] = "Done failed"
    end
  end

  def user_id
    @task = Task.find(params[:id])
    if @task.update_attribute(:user_id, params[:user_id])
      @user_r = params[:user_id]
      TaskMailer.with(user_id: @user_r, task: @task).task_assigned.deliver_now
      flash[:success] = "Member Assigned and Email sent."
      redirect_to request.referrer
    else
      flash.now[:error] = "Member Not Assigned"
    end
  end

  private

  def task_params
    params.require(:task).permit(:content, :status, :feature_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Project Management App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper

  def markdown(text)
    options = {
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      quote: true
    }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    sanitize(markdown.render(text))
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def parse_at_mentions(comment_body)
    comment_body.gsub(/@([a-zA-Z0-9_]+)/) do |match|
      user = User.find_by(name: Regexp.last_match(1))
      if user
        view_context.link_to(match, user_path(user))
      else
        match
      end
    end
  end
end

app/helpers/dash_board_helper.rb
module DashBoardHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def current_project
    @current_project = Project.find_by_id(params[:id])
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Project Management Tool", '#', id: "logo" %>
        <nav>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
              id="bs-example-navbar-collapse-1">
              <% if logged_in? %>
                <li><%= link_to "Projects", projects_path %></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Home", root_path %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: :delete %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>ProjectManagement</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="container", id = "falert" >
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_catcopy.html.erb
<div class="nexttosidebar" >
  <strong><%= "Current User:"%><%= @current_user.name %><%= " || Current Project:"%><%= @project.name.capitalize() %><%= @project.manager_name %></strong>
  <%= render 'search/form' %>
  <% @access = Access.new %>
  <% access_req = Access.where(project_id: @project.id) %>
  <% access_given = access_req.select(:user_id) %>
  <% user_access = User.where(id: access_given) %>
  <% req_id = User.where.not(id: access_given) %>
  <% task_use = {} %>
  <% user_access.each do |i| %>
    <% task_use[i.name] = i.id %>
  <% end %>
  <% if @project.manager_name == @current_user.name %>
    <div class="col-md-6 col-md-offset-3" , id="newpro">
      <%= form_with(model: @access, local: true) do |f| %>
          <%= f.hidden_field :project_id , value: @project.id.to_i %>
          <%= f.label :user_id, "Assign Member: " %>
          <%= collection_select(:access, :user_id, req_id, :id, :name, {:prompt => true, :multiple=>false }, :onchange => 'this.form.submit()')%> 
      <% end %>
    </div>
  <%end%>
  <strong><%= "Project Members: " %></strong>
  <% access_req.each do |p|%>
    <% @b= User.find_by(id: p.user_id) %>
    <%= @b.name%>
  <% end %>
  <br>
  <h3><%= @project.name.capitalize()  %> <%= " || " %><%= @cat.capitalize() %></h3>
 
  <br>
  <%= render 'shared/feature_form' %>
  <br>
	<p class="text-style"><strong>This list displays all the features of  <%= @cat.capitalize() %> and Tasks of each features if available.</strong></p> <br>
	<table class="table table-responsive table-hover" >
    <% @i = 0 %>
    <% @features.each do |feature| %>
      <% if feature.Category == @cat %>
        <% @i = @i+1 %>
        <% feature_task = Task.where(feature_id: feature.id) %>
        <tr>
          <td><strong><%= "Feature: "%><%= @i %><%= " (" %><%=feature_task.where(done: true).count()%><%= "/" %><%= feature_task.count()%><%= ")" %></strong></td>
          <td><strong><%= feature.Title %></strong></td>
          <td><strong><%= feature.Description %></strong></td>
          <% @feature_id = feature.id%>
          <td><%= render 'shared/task_form' %></td>
          <td><%= link_to 'Show', feature, :class => "btn btn-primary custom_btn_small" %></td>
        </tr>
        <% @j = 0 %>
        <% feature_task.each do |task| %>
          <% @j=@j+1 %>
          <tr>
            <td >
              <%= check_box_tag 'Done', true , task.done,
                    onchange: "$(this).data('params',  this.checked)",
                    data: { remote: true, url: done_task_path(id: task.id), method: :patch } %>
            </td>
            <td><%= "Task:" %><%= @j %></td>
            <td><%= task.content %></td>
            <td>
            <%= "Member: " %>
              <%= select_tag( 'user_id', options_for_select(task_use, { selected: task.user_id} ), prompt: "Assign Member", data:{ remote: true, url: user_id_task_path(id: task.id), method: :patch }) %>
            </td>
            <td>
            <%= "Status: " %>
              <%= select_tag( 'status', options_for_select(["Started","Finished","Delivered"], { selected: task.status } ), prompt: "Please select", data:{ remote: true, url: status_task_path(id: task.id), method: :patch }) %>
            </td>
            <td><%= link_to "Comments",edit_task_path(id: task.id), class: "btn btn-primary", role: "button" %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
	</table>
</div>

app/views/shared/_category.html.erb
<div class="nexttosidebar1" >
  <% @access = Access.new %>
  <% access_req = Access.where(project_id: @project.id) %>
  <% access_given = access_req.select(:user_id) %>
  <% user_access = User.where(id: access_given) %>
  <% req_id = User.where.not(id: access_given) %>
  <% task_use = {} %>
  <% user_access.each do |i| %>
    <% task_use[i.name] = i.id %>
  <% end %>
  <% access_req.each do |p|%>
    <% @b= User.find_by(id: p.user_id) %>
  <% end %>
  <br>
  <h3><%= @project.name.capitalize()  %> <%= " || " %><%= @cat.capitalize() %></h3>
  <br>
  <%= render 'shared/feature_form' %>
  <br>
	<p class="text-style"><strong>This list displays all the features of  <%= @cat.capitalize() %> and Tasks of each features if available.</strong></p> <br>
	<table class="table table-responsive table-hover" >
    <% @features.each do |feature| %>
      <% if feature.Category == @cat %>
        <% feature_task = Task.where(feature_id: feature.id) %>
        <tr>
          <td><strong><%= "Id: "%><%= feature.token_id %><%= " (" %><%=feature_task.where(done: true).count()%><%= "/" %><%= feature_task.count()%><%= ")" %></strong></td>
          <td><strong><%= feature.Title %></strong></td>
          <td><strong><%= feature.Description %></strong></td>
          <% @feature_id = feature.id%>
          <td><%= render 'shared/task_form' %></td>
          <td><%= link_to 'Show', feature, :class => "btn btn-primary custom_btn_small" %></td>
        </tr>
        <% @j = 0 %>
        <% feature_task.each do |task| %>
          <% @j=@j+1 %>
          <tr>
            <td >
              <%= check_box_tag 'Done', true , task.done,
                    onchange: "$(this).data('params',  this.checked)",
                    data: { remote: true, url: done_task_path(id: task.id), method: :patch } %>
            </td>
            <td><%= "Task:" %><%= @j %></td>
            <td><%= task.content %></td>
            <td>
            <%= "Member: " %>
              <%= select_tag( 'user_id', options_for_select(task_use, { selected: task.user_id} ), prompt: "Assign Member", data:{ remote: true, url: user_id_task_path(id: task.id), method: :patch }) %>
            </td>
            <td>
            <%= "Status: " %>
              <%= select_tag( 'status', options_for_select(["Started","Finished","Delivered"], { selected: task.status } ), prompt: "Please select", data:{ remote: true, url: status_task_path(id: task.id), method: :patch }) %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
	</table>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feature_form.html.erb
<%= form_with(model: @feature, local: true) do |f| %>
  <%= f.hidden_field :project_id, value: @pro_id %>
  <%= f.hidden_field :Category, value: @cat %>
  <div class="field">
    <%= f.text_area :Title, placeholder: "Feature Title", class:"form-control me-2", id: "fcreate" %>
    <%= f.text_area :Description, placeholder: "Description", class:"form-control me-2", id: "fcreate" %>
  </div>
  <%= f.submit "Create Feature", class: "btn btn-primary" %>
<% end %>

app/views/shared/_project_info.html.erb
<h1><%= current_project.name %></h1>
<span><%= link_to "view my profile", current_project %></span>
<span><%= pluralize(current_project.features.count, "feature") %></span>

app/views/shared/_sidebar.html.erb
<% if logged_in? %>
  <div class="col-sm-3 col-md-2 sidebar", id="sidebarid">
    <ul class="nav nav-sidebar">
      <p id="demo"></p>
      <li class="sidebar_back"><%= link_to "Back", projects_path %></li>
      <li class="sidebar_current_iteration"><%= link_to "Current Iteration", currentiteration_project_path %></li>
      <li class="sidebar_backlog"><%= link_to "Backlog", backlog_project_path %></li>
      <li class="sidebar_icebox"><%= link_to "Icebox", icebox_project_path %></li>
    </ul>
  </div>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>
  <%= f.hidden_field :feature_id, value: @feature_id %>
  <%= f.hidden_field :status, value: "Started" %>
  <div class="field", id="tasknew">
    <%= f.text_field :content, placeholder: "New Task: Press Enter", class:"form-control me-2", id:"taskcreate" %>
    <%#= f.submit "Create Task", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>